version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  codecov_token:
    secure: 3r3MdCJ/YIEhWCkjeMJd0AYoV0lhyXO6EWI8gQtMGPGfJA0IVWAo3mzM8qvCh54d
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
cache:
- '%USERPROFILE%\.nuget\packages -> **\*.csproj'
before_build:
- cmd: >-
    cd bxbot & yarn install & cd ..

    dotnet restore

    choco install codecov
build:
  project: bxbot-tests\bxbot-tests.csproj
  verbosity: minimal
test_script:
- cmd: >-
    %USERPROFILE%\.nuget\packages\opencover\4.6.519\tools\OpenCover.Console.exe -register:user -oldStyle -target:"c:\Program Files\dotnet\dotnet.exe" -targetargs:"test bxbot-tests.csproj" -filter:"+[bxbot]* +[bxbot-tests]* -[bxbot-tests]*Program" -output:"coverage.xml"

    codecov -f coverage.xml -t %codecov_token%
deploy: off