version: 1.0.{build}
skip_tags: true
environment:
  GitHubSonarKey:
    secure: tYQVx7/vrP730iytAlVnN4mY2+5TLTBDsezb4SiuPLEo6oI/rDZNPV0fXpwJ9qJF
  SonarKey:
    secure: QEq4s9y/UCuCthVGe2ZQCoJ9b0Bh8AtAogvTi5QdxulupzG2rOC+DHKrHy5pVG+l
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: >-
    .\runBuild.ps1
deploy: off