version: 1.0.{build}
skip_tags: true
environment:
  GitHubSonarKey:
    secure: u9ViKhJinPKbrtOwSb0mQTaMYORjGtLq5cgDYEbI/MAR7ZSPqIk7t5+pp30J0Y/X
  SonarKey:
    secure: QEq4s9y/UCuCthVGe2ZQCoJ9b0Bh8AtAogvTi5QdxulupzG2rOC+DHKrHy5pVG+l
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: >-
    .\runBuild.ps1
deploy: off