version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_branch_with_pr: true
skip_tags: true
clone_depth: 1
environment:
  SrcPath: src
  ClientApp: src\bxbot\ClientApp
  SonarExclusions: coverage\**\*,**\*.xml,**\tscoverage\*,**\*.spec.t*,**\*.js,**\tests\*,**\*.ico,**\Program.cs,**\Startup.cs,**\node_modules\*,**\wwwroot\dist\*
  SonarKey:
    secure: 12QqwTL16f53WwrFtClle28ZDS3BsHmEheUeMyT6r1BnReEnO70Vx7mzGHGLBuB9
  SonarGithubKey:
    secure: SY6rvHCSxikpJpkcDR/JsnMDc41rD9+L2w0pr370Qd1cUZJJJY4rxVISzdmTf1fG
  SonarOrg: jscoobyced-github
  SonarUrl: https://sonarcloud.io
  SonarProjectKey: bxbot
  NODE_PATH: src\bxbot\ClientApp\node_modules
  LcovInfo: .\ClientApp\tscoverage\coverage-final.json
  TsConfig: .\ClientApp\tsconfig.json
  CsTarget: test bxbot-tests\bxbot-tests.csproj
  CsFilter: +[bxbot*]* -[bxbot*]*Program -[bxbot*]*Startup +[tests*]*
  CsCoverage: coverage.xml
  TsCoverage: .\tscoverage\coverage-final.json
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
  - choco install --no-progress sonarscanner-msbuild-netcoreapp2.0
  - choco install --no-progress codecov
build_script:
  - ps: >-
      & .\scripts\build.ps1
test_script:
  - ps: >-
      & .\scripts\run_tests.ps1
after_test:
  - ps: >-
      & .\scripts\after_test.ps1
artifacts:
  - path: publish
    type: Zip
deploy:
  - provider: AzureAppServiceZipDeploy
    name: production
    on:
      branch: master
    appservice_environment: false
    website: bxbot
    username: bxbot
    password:
      secure: 7Abb6Ut61PC0yff1dUy1HfYCOLwckof/tWSofCDbvqs/AVUtkbnNIvPzl2bt4fwj
    artifact: publish.zip
notifications:
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
